# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.5'

services:
  test-httpd:
    container_name: "my-hc-tests-httpd"
    image: "hc-tests-httpd:latest"
    ports:
      - "8080:80"
  test-nginx:
    container_name: "my-hc-tests-nginx"
    image: "hc-tests-nginx:latest"
    ports:
      - "8081:80"
  test-httpbin:
    container_name: "my-hc-tests-httpbin"
    image: "hc-tests-httpbin:latest"
    ports:
      - "8082:80"
